FROM oracle/graalvm-ce:20.1.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/micronaut-demo
WORKDIR /home/app/micronaut-demo

RUN native-image --no-server -cp build/libs/micronaut-demo-*-all.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/micronaut-demo/micronaut-demo /app/micronaut-demo
ENTRYPOINT ["/app/micronaut-demo"]